### PR TITLE
fixes for SES

### LINKED ISSUE #13: SES bounce handling
Currently there are issues with bounce handling for SES and is not working as expected.

### PR DESCRIPTION
**Pull request by kurund**
Fixes #13

### CODE REVIEW

**Comment by kurund** [comment]
Hey @agh1 it would be good to get this merged. Let me know if anything is needed.

**Comment by michaelmcandrew** [comment]
@agh1 - hope all is well with you - let me know if there is anything we can do to get this merged?

Are you interested in any help maintaining this extension? We would be happy to do so if you like.

**Comment by michaelmcandrew** [comment]
thanks @alifrumin - might have another PR for you on its way soon.

Michael

**Comment by alifrumin** [comment]
No problem, thanks for contributing. Let us know!

**Pull request merged**
